// Dialog for registering the Pinellas-paga reembolso (separate from the
// reembolso flow generated by closing a caja menuda).
// Lifted out of SolicitudesPagoGeneral.tsx and ProjectSolicitudesPago.tsx
// during the refactor of issue #26.

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface RegistrarReembolsoPinellasDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  fecha: string;
  onFechaChange: (value: string) => void;
  file: File | null;
  onFileChange: (file: File | null) => void;
  loading: boolean;
  onConfirm: () => void;
}

export function RegistrarReembolsoPinellasDialog({
  open,
  onOpenChange,
  fecha,
  onFechaChange,
  file,
  onFileChange,
  loading,
  onConfirm,
}: RegistrarReembolsoPinellasDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px]">
        <DialogHeader>
          <DialogTitle>Registrar Reembolso</DialogTitle>
          <DialogDescription>
            Registra el comprobante del reembolso a Pinellas.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 space-y-4">
          <div>
            <Label>Fecha de reembolso *</Label>
            <Input
              type="date"
              value={fecha}
              onChange={(e) => onFechaChange(e.target.value)}
              className="mt-1"
            />
          </div>
          <div>
            <Label>Comprobante *</Label>
            <Input
              type="file"
              accept=".pdf,.jpg,.jpeg,.png"
              onChange={(e) => onFileChange(e.target.files?.[0] || null)}
              className="mt-1"
            />
          </div>
        </div>
        <DialogFooter className="gap-2 sm:gap-0">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancelar
          </Button>
          <Button
            onClick={onConfirm}
            disabled={!fecha || !file || loading}
          >
            {loading ? 'Registrando...' : 'Confirmar Reembolso'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
